### ISSUE TITLE
Some shown private datasets cannot be deleted

### ISSUE THREAD

**Issue by sunbrn** [acanakoglu/GMQL-WEB#2]
For some reason I cannot delete all my datasets that were created on the 30th of May. It says "These datasets cannot be deleted".

I am talking about these:

![image 1](https://cloud.githubusercontent.com/assets/11488353/19346087/ed073c00-9141-11e6-8478-4bfe97af5b5e.png)

My guess is that some changes were made in the repository, memory location were these were stored and now the web interface shows them but has lost the pointer..

**Comment by sunbrn** [comment]
How do I understand where my datasets are? I only know that I was using the interface on CINECA

**Comment by acanakoglu** [comment]
It was because of an older bug. For now, we deleted erroneous dataset directly with @akaitoua.
